### ISSUE TITLE
I love where you're going with this.  But your "getting started" is overly complicated.

### ISSUE THREAD

**Issue by SharePointShop** [koltyakov/sp-jsom-node#4]
I appreciate you're a type script fan. As we both now, there are now better ways to customize SharePoint.  Yet, there are still use cases for this approach.  And I'm facing one. 

The sugar of TypeScript and Promises are more overhead than assets in this scenario given React.  How about a straight forward example of raw JavaScript connecting from remote, without the preconditions of loading a settings file that I've yet to find a good example of each authentication model?  I appreciate the hard work.  SharePoint auth is a pain!  Since you cracked the nut, please provide a "clean" example so we don't have to unpack your logic and can fully appreciate the rewards of your hard work.  This module could offer a more valuable asset to the community then those popular in days of old like SPServices.  Especially when it comes to rapid development using NodeJS. It has even more potential but lacks a basic getting started without the overhead of sugar, as enjoyable as sugar can be.  
  
Thanks again!  Super impressive value add.

**Comment by koltyakov** [comment]
Hi Jonathan and thank you for the interest, and your words!

I'm wondering what can be simplified in the getting started section? It has both TypeScript and JavaScript examples. There is even a gif which represents the install and simple usage example.

Is it about TypeScript itself? Or other generic Node.js parts?

Does the following sounds less complicated:

## Prerequisites

- Node.js

## Dependencies

```bash
npm i sp-jsom-node
```

## Create a script

For instance, `index.js`:

```javascript
//@ts-check
const { JsomNode } = require('sp-jsom-node');

new JsomNode().wizard().then(_ => {

  /// ... <<< JSOM can be used in here
  const ctx = SP.ClientContext.get_current();

}).catch(console.log);
```

## Run the script

```bash
node ./index.js
```

On the first run, it asks for credentials and dumps them to disk in `./config/private.json` to reuse on next run.

> loading a settings file that I've yet to find a good example of each authentication model

No need to craft the configs manually, by default, then no configs are provided to the initiator class, it assumes that the config is stored in `./config/private.json`. If no config exists the prompts wizard appears asking for URL, strategy, login, etc.

About promises, it's a simple and powerful language feature which is used nowadays almost in any modern library, bringing a lot of programming benefits, especially with async/await combination, I always consider promises support as simplification rather than the opposite.

Regard "clean" example, the above-mentioned one is torn out from the index README.md, can't imagine any simpler than that.

Please share your ideas for simplification.
